stages:
  - test
  
services:
  - docker:27.4.1-dind

before_script:
  - apt-get update
  - apt-get install -y docker-compose
  - docker info

test:
  stage: test
  image: docker:27.4.1
  script:
    - sudo apk add dotnet8-sdk
    - dotnet test