stages:
  - test

services:
  - name: docker:27.4.1-dind
    alias: docker

before_script:
  - docker info

test:
  stage: test
  image: docker:27.4.1
  script:
    - sudo apk add dotnet8-sdk
    - dotnet test