variables:
  DOCKER_TLS_CERTDIR: "/certs"

test:
  stage: test
  image: docker:27.4.1

  services:
    - docker:27.4.1-dind

  script:
    - docker info
    - apk add dotnet8-sdk
    - docker-compose up -d
    - dotnet test