services:
  service-1:
    build:
      context: ./service-1
    ports:
      - "8081:8080"
    depends_on:
      service-2:
        condition: service_started

  service-2:
    build:
      context: ./service-2
