name: devops-compose-experiment
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8198:8198"
    depends_on:
      service-1-1:
        condition: service_started

  service-1-1:
    build:
      context: ./service-1
    depends_on:
      service-2:
        condition: service_started

  service-1-2:
    build:
      context: ./service-1
    depends_on:
      service-2:
        condition: service_started

  service-1-3:
    build:
      context: ./service-1
    depends_on:
      service-2:
        condition: service_started

  service-2:
    build:
      context: ./service-2
