name: devops-compose-experiment
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8198:8198"
      - "8197:8197"
    depends_on:
      service-1-1:
        condition: service_started

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  service-1-1:
    build:
      context: ./service-1
    depends_on:
      db:
        condition: service_started
      service-2:
        condition: service_started

  service-1-2:
    build:
      context: ./service-1
    depends_on:
      db:
        condition: service_started
      service-2:
        condition: service_started

  service-1-3:
    build:
      context: ./service-1
    depends_on:
      db:
        condition: service_started
      service-2:
        condition: service_started

  service-2:
    build:
      context: ./service-2

volumes:
  mongo-data: